### ISSUE TITLE
Validate constant injectionRate at Policy configuration time

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#15]
The [`MonkeyPolicy` implementations validate `injectionRate` at run-time](https://github.com/App-vNext/Simmy/blob/v0_1/src/Simmy/MonkeyEngine.cs#L18-L25).

For those policy configuration overloads which take a `Double injectionRate` at configuration-time, it would be nice to have the same validation at configuration-time rather than at run-time.

[Example overload](https://github.com/App-vNext/Simmy/blob/v0_1/src/Simmy/Fault/InjectFaultSyntax.cs#L19); there are many others.

_Nice-to-have: not essential for go-live_

**Comment by mebjas** [comment]
+1 on this. Same goes for `fault` argument. I can take this up.
