### ISSUE TITLE
Add overloads taking CancellationToken, for async configuration-providing delegates

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#19]
As @martincostello mentions [here](https://github.com/App-vNext/Polly/pull/508#issuecomment-429633094), given the Simmy API does offer async overloads to obtain configuration values in the async cases, those APIs might want take to a `CancellationToken`.

We would need to agree what the assumptions should be if cancellation was signalled for a config-obtaining delegate:

+ for delegates returning `bool enabled`, we would probably have no option but to assume cancellation means we return `false`
+ for delegates returning `injectionRate` or `Timespan` we would probably likewise have no _better_ option than to assume cancellation means the fault-injection operation should default to _not_ injecting the fault

_Thoughst?_

---

x-ref: #18 affects same APIs

**Comment by vany0114** [comment]
Yes, absolutely agree, We can't assume a default value for `injectionRate` or `enabled` parameters (other than `0` and `false`). @reisenberger when you say `Timespan` you mean the delegate to get the latency value and not the latency injected itself that we're going to implement in #20 right? if so, we need to do so with `Exception/TResult` as well

**Comment by reisenberger** [comment]
>when you say Timespan you mean the delegate to get the latency value [...] if so, we need to do so with Exception/TResult as well

Hi @vany0114 . Yes, exactly that.  

Actually, it looks like there are already overloads configuring delegates which take `CancellationToken` for obtaining [the latency](https://github.com/Polly-Contrib/Simmy/blob/1ec059c0bef75d5af939b81341554732194ca93e/src/Polly.Contrib.Simmy/Latency/AsyncInjectLatencySyntax.cs#L82), the [fault exception](https://github.com/Polly-Contrib/Simmy/blob/1ec059c0bef75d5af939b81341554732194ca93e/src/Polly.Contrib.Simmy/Fault/AsyncInjectFaultSyntax.cs#L62), [fault result](https://github.com/Polly-Contrib/Simmy/blob/1ec059c0bef75d5af939b81341554732194ca93e/src/Polly.Contrib.Simmy/Fault/AsyncInjectFaultSyntax.cs#L198) and [behaviour](https://github.com/Polly-Contrib/Simmy/blob/1ec059c0bef75d5af939b81341554732194ca93e/src/Polly.Contrib.Simmy/Behavior/AsyncInjectBehaviourSyntax.cs#L88) configurations, so it is really just the `Func<... Task<T>>` format for `injectionRate` and `enabled` ([like this](https://github.com/Polly-Contrib/Simmy/blob/1ec059c0bef75d5af939b81341554732194ca93e/src/Polly.Contrib.Simmy/Latency/AsyncInjectLatencySyntax.cs#L83-L84) but throughout) which maybe could benefit from the addition of `CancellationToken` overloads.

What do you think?

I have learnt with Polly that - with the current syntax model - it is easy for numbers of overloads to proliferate by adding new possibilities.  Worth considering not to add every possible combination, or even whether to _replace_ existing most-complex overloads with ones which also take a `CancellationToken` input parameter in those cases.

(The longer-term solution to the many-configuration-overloads problem is to change the syntax to `.PolicyType(Action<IPolicyTypeConfiguration>)`, which allows new features to be added more flexibly. I plan this for Polly sometime. You could experiment with this for Simmy now if you prefer!)

**Comment by reisenberger** [comment]
Another question arises: if the delegates to asynchronously retrieve configuration for latency, Exception or TResult can take `CancellationToken` - what `CancellationToken` value should the Simmy policies actually _pass_ when executing those configuration delegates?

(i) The `CancellationToken` passed through the Polly execution as a whole (passed in to the `.ExecuteAsync(...)` where Polly is used) governs cancelling the execution as a whole.  It would make sense for configuration delegates at least to honour this.

(ii) But that's not the same as a short timeout on obtaining chaos configuration. If we want to add the feature of a short timeout on obtaining chaos configuration, then either:
  - (a) we also have to extend all the Simmy APIs to receive that timeout, and combine in a timing-out cancellation token with the token from (i) above; OR
  - (b) we say that timeout is something that Polly already handles well, with `TimeoutPolicy`, and users can just use existing Polly `TimeoutPolicy` _within_ their configuration delegate.  

Thoughts?

**Comment by vany0114** [comment]
> (The longer-term solution to the many-configuration-overloads problem is to change the syntax to .PolicyType(Action<IPolicyTypeConfiguration>), which allows new features to be added more flexibly. I plan this for Polly sometime. You could experiment with this for Simmy now if you prefer!)

Hi @reisenberger, I agree, I remember you told me about that idea before, and I think it's great! since it will allow Simmy to grow easier, so having said that, once we finished with that new syntax, I think we can implement the scenario you explained above (receiving a timeout for configuration delegates --should be easier then--) and for now, just let people handle it using Polly.

In the meantime, I can create a PR to allow the `injectionRate` and  `enabled` guys are cancellable. What do you think?

P.S: after that, I can start to work on the new syntax.

**Comment by reisenberger** [comment]
@vany0114 , Sounds like a great plan, please go ahead!  It's awesome working with you on Simmy and we are really happy for you to drive ideas and make recommendations like this.  💯 👍 🙏

**Comment by vany0114** [comment]
My pleasure @reisenberger, I'm very happy working with you guys, I'm learning a lot!
