### ISSUE TITLE
Injected latency should be cancellable

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#20]
Currently, latency injected by `MonkeyPolicy.InjectLatency(...)` or `MonkeyPolicy.InjectLatencyAsync(...)` is [not cancellable](https://github.com/App-vNext/Simmy/blob/c6f05d090d0282ef2266065895c64d14d04d2a7d/src/Simmy/Latency/InjectLatencyPolicy.cs#L13), in either the sync ([1](https://github.com/App-vNext/Simmy/blob/c6f05d090d0282ef2266065895c64d14d04d2a7d/src/Simmy/Latency/InjectLatencyPolicy.cs#L33); [2](https://github.com/App-vNext/Simmy/blob/c6f05d090d0282ef2266065895c64d14d04d2a7d/src/Simmy/Latency/InjectLatencyPolicy.cs#L63)) or async ([1](https://github.com/App-vNext/Simmy/blob/c6f05d090d0282ef2266065895c64d14d04d2a7d/src/Simmy/Latency/AsyncInjectLatencyPolicy.cs#L38); [2](https://github.com/App-vNext/Simmy/blob/c6f05d090d0282ef2266065895c64d14d04d2a7d/src/Simmy/Latency/AsyncInjectLatencyPolicy.cs#L75)) implementations.

### Async case

Not allowing cancellation doesn't seem right in the async case.  Async APIs of typical systems called through Polly typically support cancellation.  By providing a  `MonkeyPolicy.InjectLatencyAsync(...)` that _doesn't_ support cancellation, we don't allow users to test how their production system would respond if there was (say) an extra 20ms latency.

For example, if the call is to some Azure SDK API which accepts a `CancellationToken` and the user is using an `TimeoutPolicyAsync()` or their own timing-out `CancellationToken`, then the call would typically cancel when the token is signalled. To allow users to simulate (in prod; or unit tests) that that behaviour works, the injected latency would want to be cancellable too.

_Recommend:_ Change  `MonkeyPolicy.InjectLatencyAsync(...)` to honour the CancellationToken passed to the `.ExecuteAsync(...)` call through the policies. 

_Option (now or later):_ Add an `bool isCancellable` parameter to (some) overloads of `MonkeyPolicy.InjectLatencyAsync(...)`, allowing the user _choice_ over whether they are injecting cancellable or non-cancellable latency. 

### Sync case

The sync case seems opposite. Sync APIs _typically_ don't support cancellation.  Therefore, it would be a more realistic simulation for the sync `MonkeyPolicy.InjectLatency(...)` to _not_ support cancellation, at least by default.

_Recommend:_ Leave `MonkeyPolicy.InjectLatency(...)` not honouring the CancellationToken passed to the `.Execute(...)` call through the policies. 

_Option (now or later):_ Add an `bool isCancellable` parameter to (some) overloads of `MonkeyPolicy.InjectLatency(...)`, allowing the user _choice_ over whether they are injecting cancellable or non-cancellable latency.

**Comment by mebjas** [comment]
Makes sense, the Async implementation should have cancellation support. I could have the injection deep in the call stack while cancellation could be signaled from much top layer.
