### ISSUE TITLE
Bring Simmy code over from the Polly repo

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#4]
#### Bring Simmy code over from the Polly repo

Bring exactly the `Monkey` folders (code, and tests) over from https://github.com/App-vNext/Polly/pull/553 .  (Code may not need to be in `Monkey` sub-folders when part of the Simmy repo.)

After #2.  After Polly v7.0 released.

New code will need to take a dependency (stated in nuspec; csprojs) on Polly >= v7.0

**Comment by vany0114** [comment]
I can take care of this!

**Comment by vany0114** [comment]
@reisenberger I have several questions here:

* I can work on #2 as well since it's a pre-requisite, or maybe @mebjas want to?
* Should I create a dev branch then a PR when this work is done or I can push directly to master?
* Do we need to wait until Polly v7.0 will be released to start to work on this, right?

**Comment by reisenberger** [comment]
Thanks @vany0114 for picking this up!  Sorry for delayed answer!  

>I can work on #2 as well since it's a pre-requisite, or maybe @mebjas want to?
>Do we need to wait until Polly v7.0 will be released to start to work on this, right?

Yep, #2 needs to be done first, then we can pick off #3 and #4 (in either order).  
#1, #2, and #3 can be done before Polly v7.0 is released; #4 and #7 (7 with joel) have to be done after Polly v7.0 is released.

>Should I create a dev branch then a PR when this work is done or I can push directly to master?

Yeah, let's still do branch and PR - it's a good practice we even (Joel + I) follow rigorously on the Polly repo, easier to discuss anything (if needed), and makes sure `master` always clean.  But very happy that we move through the PRs quickly (I will try to be very responsive) as we get this set up.  

Thanks again for everything you have done and are doing!  I think Simmy is going to be very exciting!

**Comment by mebjas** [comment]
> * I can work on #2 as well since it's a pre-requisite, or maybe @mebjas want to?

@vany0114 It's fine with me, please go ahead. I'd like the feature to roll out ASAP as biggest priority :)

**Comment by mebjas** [comment]
`just a suggestion`
idk if it's common to use but we could leverage this - https://github.com/App-vNext/Simmy/projects for project management in place of using issues

**Comment by reisenberger** [comment]
hi @mebjas ! I've used the github project boards before. They don't replace github issues and PRs, but do allow you to drag them through status columns if you want to.  Here's a past [example, from the major launch of Polly v5](https://github.com/App-vNext/Polly/projects/1).

Just say, if either of you think it'd be helpful, and I'll set one up!  Thanks again!

**Comment by mebjas** [comment]
I guess for now issues would do. If we start implementing a log of features
we could use it ;)

It'd be fun to see everything completed, like in the shared link. I don't
get to seem them like that at work :D

**Comment by vany0114** [comment]
Ok, guys, I'm gonna try to do that tonight, I imagine that @reisenberger has to give me some permissions to create a branch and push commits? On the other hand, I think the project board is pretty nice for people interested in the project, as they could know what's going on with the project 😄

**Comment by vany0114** [comment]
#2 and #3 are done, waiting for dev branch to do the PR 😃

**Comment by joelhulen** [comment]
@vany0114 Thanks for the contribution! As opposed to needing to have write access to the repo, the standard procedure we use (even the core team) is to fork the repo, create your feature branch there and make your changes, then issue a PR from your fork.

Please refer to the [Git Workflow article](https://github.com/App-vNext/Polly/wiki/Git-Workflow) in the Polly wiki.

**Comment by vany0114** [comment]
Hi @joelhulen, yeah you're right, but I'm gonna need the branch to target my PR to, anyways right? Since this repo only has a master branch.

**Comment by reisenberger** [comment]
@vany0114 Awesome, thank you! I just made a `v0_1` branch.  (Not pre-judging the decision on #5, first version number, but it seemed as good a place to start as any for the branch name.). Thanks again!

**Comment by joelhulen** [comment]
@vany0114 Ha, yes I suppose so :) Looks like @reisenberger took care of you there. Thanks!

**Comment by reisenberger** [comment]
@vany0114 @mebjas (whoever wants to pick up a next step)

#8 is merged.  I previously wrote that we cannot pursue this #4 (Bring Simmy code over from the Polly repo) until Polly v7.0.0 is released to nuget. But actually we can prepare a PR on Simmy to bring the code across right now (before Polly v7.0.0 is released), by referencing a local nuget package build of Polly.  Thus:

+ Check out [the Polly v7.0.0 branch](https://github.com/App-vNext/Polly/tree/v700) and run the build locally
+ A nuget package will be written to the `artifacts\nuget-package` directory.  Probably called something like `Polly.7.0.0-v700-0001.nupkg`
+ Drop that package into a [local nuget feed on your local machine](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds)
+ Bring the Simmy code over from  App-vNext/Polly#553 , referencing the local `Polly.7.0.0-v700-0001.nupkg`

If we prepare a PR per above on Simmy, we can't ~_merge_~ (**EDIT**) release it until Polly v7.0.0 is released public, but we can get ahead by preparing that way ...

**EDIT**: I am working on the v7 custom policy doco, sample custom policy repos, etc

**Comment by vany0114** [comment]
I can work on that!

**Comment by vany0114** [comment]
@reisenberger a couple of things:

* Polly v7.0.0 branch doesn't have the implementation of `ThreadSafeRandom_LockOncePerThread` 
* Simmy unit tests has a reference to `Polly.Specs.Helpers.Constants.SystemClockDependentTestCollection` but obviously  Polly nuget package doesn't have the specs dll. So, should we move `Constants.SystemClockDependentTestCollection` to Polly dll or we should create that constant inside Simmy?

**Edit:** same thing with `ResultPrimitive`

**Comment by reisenberger** [comment]
@vany0114 Great questions! 

In both cases, let's reduce coupling between the Simmy package and Polly package as much as possible, so that the only point of join/dependency is how the custom policies extend base classes.  So:

>should we move Constants.SystemClockDependentTestCollection to Polly dll or we should create that constant inside Simmy?

Let's create an equivalent constant inside Simmy.

>Polly v7.0.0 branch doesn't have the implementation of ThreadSafeRandom_LockOncePerThread

Let's have this class in a namespace `Simmy.Utilities` rather than in Polly.

Thanks again!

**Comment by reisenberger** [comment]
Closed by #13
