### ISSUE TITLE
Implement new syntax

### ISSUE THREAD

**Issue by vany0114** [Polly-Contrib/Simmy#42]
Implement the new syntax to avoid the proliferation of overloads in order to allow Simmy can grow easier and the new features can be added more flexibly avoiding breaking changes and deprecate too much code.

Syntax proposal:
```
.PolicyType(Action<IPolicyTypeConfiguration>)
```

Example:
```
var policy = MonkeyPolicy.InjectLatency(options => 
   {
        options.Latency = TimeSpan.FromMilliseconds(5),
        options.InjectionRate = 0.1,
        options.Enabled = true
   };
);
```

**Comment by salem84** [comment]
Hi @vany0114!
If you agree, I could work on it!
