### ISSUE TITLE
Decide launch version number

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#5]
Decide whether we launch Simmy as a [semver version number](https://semver.org/):

+ 0.1 : _if_ we consider 'early' version
+ 0.9 ; if we are holding off a 1.0 at launch, but to indicate we are close to a 1.0 and confident in the product and public API  (as feels like we will be)
+ 1.0 : to indicate this is the public API, we are confident in the public API not changing.

For decision as we go over any final clean-up of the code.

Comment welcome.

**Comment by reisenberger** [comment]
Seems like v0.1.0 is a good launch version number, and the proper number by semver.  The numbering gives room still to improve the API for the unit-testing case use case - where we may want a slightly different API - before saying the API is fixed/stable at v1.0.0.

Is that an ok decision, @mebjas @vany0114 ?

**Comment by vany0114** [comment]
@reisenberger makes totally sense.

**Comment by mebjas** [comment]
Yup

**Comment by reisenberger** [comment]
Closed by team agreement: v0.1
