### ISSUE TITLE
Add support for .Net Standard 2.1

### ISSUE THREAD

**Issue by vany0114** [Polly-Contrib/Simmy#50]
We need to add support for .Net Standard 2.1 since it's already released.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by josephwoodward** [comment]
@vany0114 Just a heads up that this issue can now be closed.

**Comment by vany0114** [comment]
@JosephWoodward thanks for the heads up, I'm just waiting to close all the issues related with the `v3` which is going to be released soon. BTW that version will include your contribution!
