### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#6]
We have an offer from a member of the App-vNext team to create a logo ...

**Comment by mebjas** [comment]
What's the logo idea?

**Comment by reisenberger** [comment]
Hi @mebjas .  @joelhulen (man of many talents) is our artist, he already designed the Polly logo.  I alerted Joel to the [logo discussion on the Polly repo](https://github.com/App-vNext/Polly/pull/508#issuecomment-443499156), there was some discussion that it would be nice if the logo could somehow incorporate the letters **S**, **mm** or **y** from Simmy into the monkey similar to how the [Polly logo incorporates the **ll** of Polly in the feet](https://github.com/App-vNext/Polly/blob/master/Polly-Logo.jpg), but really it's up to / over to Joel ...

**Comment by mebjas** [comment]
Sounds cool!

**Comment by reisenberger** [comment]
Closed by https://github.com/Polly-Contrib/Simmy/commit/9f8ee9c7b3ed591613f0b315d2a89888fb911781 and following commits.
