### ISSUE TITLE
'InjectLatencyAsyncOptions' does not contain a definition for 'Latency'

### ISSUE THREAD

**Issue by asasine** [Polly-Contrib/Simmy#64]
I'm trying to follow the README's example on using the Latency handler and am receiving this error with the new syntax.

> 'InjectLatencyAsyncOptions' does not contain a definition for 'Latency' and no accessible extension method 'Latency' accepting a first argument of type 'InjectLatencyAsyncOptions' could be found (are you missing a using directive or an assembly reference?)

Here is my code for reference:

```csharp
var latencyPolicy = MonkeyPolicy.InjectLatencyAsync<HttpResponseMessage>(with =>
    with.Latency(TimeSpan.FromSeconds(5))
        .InjectionRate(1.0)
        .Enabled(true)
    );
```

For what it's worth, the obsolete syntax works, though it warns of [CS0618](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-messages/cs0618) when compiled.

```csharp
var latencyPolicy = MonkeyPolicy.InjectLatencyAsync<HttpResponseMessage>(TimeSpan.FromSeconds(5), 1.0, () => true);
```

I am using Polly.Contrib.Simmy version 0.3.0

**Comment by vany0114** [comment]
I think you're missing this `using` statement:
```
using Polly.Contrib.Simmy.Latency;
```

**Comment by asasine** [comment]
Thanks!
