### ISSUE TITLE
are there samples for using simmy with polly v8 constructs?

### ISSUE THREAD

**Issue by cbertolasio** [Polly-Contrib/Simmy#68]
Hello, I tried to check this out in the slack channel but was not able to get in there.  I have been trying to figure out if there are any samples of how to add simmy policies to polly v8 pipelines?

For example, I have created a ResiliencePipelineRegistry and added a Retry and NoOp pipeline to the registry.  These items, since they are v8 polly contructs use a ResilienceContext.  

Later on down in the code, if my app is in development mode, I try to AddChaosInjectors to the registry using an extension method that should iterate the pipelines in the registry and add MonkeyPolicies dynamically based on configuration values that are stored in the Context.

v7 of Polly uses Context.  v8 of Polly uses ResilienceContext.  Do the config values added to the ReslienceContext somehow get copied to a Context and should the expectation be that polly v8 can work with ResilienceContext and MonkeyPolices can still use Context?

Its just unclear how to attach MonkeyPolicy to v8 ResiliencePipelines so are there any samples for that or is it just not supported yet.

**Comment by vany0114** [comment]
@cbertolasio that's in the works! The new version of Simmy will be released soon. 

Spoiler alert: Simmy will be included in the Polly package.

**Comment by cbertolasio** [comment]
ok great, that sounds awesome, so for now, i will just hold fast and wait and I will make my app just use polly v8 and all of its new hotness and whenever simmy rolls out, I will re-evaluate it

thanks for the feedback.

**Comment by vany0114** [comment]
Hi @cbertolasio the new Simmy is already available in the [Polly](https://github.com/App-vNext/Polly) `8.3.0`, look at the [docs](https://www.pollydocs.org/chaos/index.html) for more information, looking forward to your feedback!
